### ISSUE TITLE
7* - Sửa lỗi CM

### ISSUE THREAD

**Issue by ngthienkhang** [ngthienkhang/CNPMNC_OKA2#11]
- [ ] Sửa Project plan: xem lại thứ tự việc trong sprint, thêm thời gian trong plan, thêm thông tin còn thiếu
- [x] Sửa đặc tả usercase: coi lại những chỗ có "Sách", chỉnh lại flow chỉ lấy 1 luồng sử dụng 
- [ ] Sửa database/ERD: thống nhất lại những bảng có trong DB, các field của Bảng, quan hệ và khóa 
- [ ] Sửa lại quản lý folder 
- [x] Đẩy DB lên host : tạm thời chọn heroku, tránh để lố dung lượng free

**Comment by ngthwng** [comment]
Đã sửa Đặc tả và push lên

**Comment by ngthienkhang** [comment]
Đã tìm được host
